# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[r7l]
location = /var/db/repos/r7l
sync-type = git
sync-uri = https://github.com/rakher/r7l.git
