# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[CachyOS-kernels]
location = /var/db/repos/CachyOS-kernels
sync-type = git
sync-uri = https://github.com/Szowisz/CachyOS-kernels.git

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git

[pingwho-overlay]
location = /var/db/repos/pingwho-overlay
sync-type = git
sync-uri = https://github.com/jaypeche/pingwho-overlay.git

[arrans-overlay]
location = /var/db/repos/arrans-overlay
sync-type = git
sync-uri = https://github.com/arran4/arrans_overlay.git
