# - Make sure user is in wheel file. 

# Persist root access for all commands
#permit persist ram as root

permit persist :wheel


# Allow tee writes to CPU freq files without password prompt
permit persist ram as root cmd tee args /sys/devices/system/cpu/cpu*/cpufreq/*

# Optional: other nopass commands
permit nopass :wheel cmd cryptsetup
permit nopass :wheel cmd mount
permit nopass :wheel as root cmd /usr/bin/hyprpm

permit nopass :wheel as root cmd /sys/power/state
permit nopass :wheel as root cmd shutdown
permit nopass :wheel as root cmd reboot
