general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# turn off keyboard backlight
listener {
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}


# If sound is NOT running, and screen is NOT changing, lock computer after 15 seconds.
listener {
    timeout = 15
    #on-timeout = bash -c 'hyprctl activewindow | grep -q "fullscreen: 1" || pactl list sink-inputs | grep -q "State: RUNNING" || hyprlock -c ~/.config/hyprlock/layouts/layout2/hyprlock.conf'
    #on-timeout = bash -c '! (hyprctl clients | grep -q "fullscreen: 1" || pactl list sink-inputs | grep -q "State: RUNNING" || pw-cli ls Node 2>/dev/null | grep -qi "running" || pgrep -fa sunshine || pgrep -fa moonlight || pgrep -fa steam || pgrep -fa com.valvesoftware.Steam || pgrep -fa gamescope || ( [ -f /sys/class/drm/card0/device/gpu_busy_percent ] && [ "$(cat /sys/class/drm/card0/device/gpu_busy_percent)" -gt 3 ] ) || ( command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi dmon -s u -c 1 | awk '\''NR==3 {exit !($6>0)}'\'' ) || [ "$(hyprctl idle)" -le 10 ]) && hyprlock -c ~/.config/hyprlock/layouts/layout2/hyprlock.conf'
    on-timeout = bash -c '! (hyprctl clients | grep -q "fullscreen: 1" || pactl list sink-inputs | grep -q "State: RUNNING" || pw-cli ls Node 2>/dev/null | grep -qi "running" || pgrep -fa sunshine || pgrep -fa moonlight || pgrep -fa steam || pgrep -fa com.valvesoftware.Steam || pgrep -fa gamescope || pgrep -fa retroarch || pgrep -fa lutris || pgrep -fa heroic || pgrep -fa wine || pgrep -fa mangohud || ( [ -f /sys/class/drm/card0/device/gpu_busy_percent ] && [ "$(cat /sys/class/drm/card0/device/gpu_busy_percent)" -gt 3 ] ) || ( command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi dmon -s u -c 1 | awk '\''NR==3 {exit !($6>0)}'\'' ) || [ "$(hyprctl idle)" -le 10 ]) && hyprlock -c ~/.config/hyprlock/layouts/layout2/hyprlock.conf'
