address_family = both
capture = wlr
gamepad = ds5
lan_encryption_mode = 0
notify_pre_releases = enabled
output_name = 1
stream_audio = true
system_tray = enable
upnp = enabled
wan_encryption_mode = 0
