[window]

opacity = 0.7

[window.dimensions]
columns = 150
lines = 35

[general]
import = ["colors.toml"]

[keyboard]
bindings = [
  # Alt+C to copy
  { key = "C", mods = "Alt", action = "Copy" },
  # Alt+V to paste
  { key = "V", mods = "Alt", action = "Paste" },
  { key = "C", mods = "Control|Shift", chars = "\u0003"}
]
